mock-ee/pom.xml
mock-ee/src/main/java/gov/va/api/med/mockee/ConnectionGenerator.java
mock-ee/src/main/java/gov/va/api/med/mockee/EeResponseRepository.java
mock-ee/src/main/java/gov/va/api/med/mockee/EeSummaryEndpoint.java
mock-ee/src/main/resources/application.properties
mock-ee/src/test/java/gov/va/api/med/mockee/ApplicationTest.java
mock-ee/src/test/java/gov/va/api/med/mockee/ApplicationTests.java
mock-ee/src/test/java/gov/va/api/med/mockee/ConnectionGeneratorTest.java
mock-ee/src/test/java/gov/va/api/med/mockee/EeSummaryEndpointTest.java
src/scripts/make-configs.sh

Refactored the application to improve code coverage.

Task/CCE-25: Improving Mock-EE code coverage

---

mock-ee/src/main/docker/entrypoint.sh

JIRA Issue:
https://vasdvp.atlassian.net/browse/CCE-52
Updated the smoke & regression tests to include the version in the path.

Added versioning to smoke and regression tests

---

.gitignore
mock-ee/pom.xml
mock-ee/src/main/java/gov/va/api/health/mockee/Application.java
mock-ee/src/main/java/gov/va/api/health/mockee/EeResponseEntity.java
mock-ee/src/main/java/gov/va/api/health/mockee/EeSummaryEndpoint.java
mock-ee/src/main/java/gov/va/api/health/mockee/Exceptions.java
mock-ee/src/main/java/gov/va/api/health/mockee/WebServiceConfig.java
mock-ee/src/main/java/gov/va/api/health/mockee/healthcheck/SteelThreadSystemCheck.java
mock-ee/src/main/java/gov/va/api/health/mockee/healthcheck/SteelThreadSystemCheckLedger.java
mock-ee/src/main/java/gov/va/api/health/mockee/healthcheck/SteelThreadSystemCheckLedgerImpl.java
mock-ee/src/test/java/gov/va/api/health/mockee/ApplicationTest.java
mock-ee/src/test/java/gov/va/api/health/mockee/EeSummaryEndpointTest.java
mock-ee/src/test/java/gov/va/api/health/mockee/JpaTest.java
mock-ee/src/test/java/gov/va/api/health/mockee/healthcheck/SteelThreadHealthCheckTest.java
mock-ee/src/test/java/gov/va/api/health/mockee/healthcheck/SteelThreadSystemCheckLedgerImplTest.java

JIRA Issue: https://vasdvp.atlassian.net/browse/CCE-74
Renamed groupid and package to match promototron required `.health` instead of `.med`

Renamed groupid and package to match promototron required 

---

Jenkinsfile
mock-ee-tests/pom.xml
mock-ee/pom.xml
pom.xml
src/scripts/dev-app.sh

https://vasdvp.atlassian.net/browse/API-1438
depends on https://github.com/department-of-veterans-affairs/health-apis-eligibility-and-enrollment-client/pull/23

API-1438 java 12 upgrade

---

mock-ee/pom.xml
mock-ee/src/main/java/gov/va/api/health/mockee/EeResponseEntity.java
mock-ee/src/test/java/gov/va/api/health/mockee/EeSummaryEndpointTest.java
mock-ee/src/test/java/gov/va/api/health/mockee/Updaterator.java

https://vasdvp.atlassian.net/browse/CCE-133
Updaterator script for changes to Mock-EE data.
Script was executed to add patient latitude and longitude to 80% of Mock-EE records in MITRE database.

CCE-133 Add patient lat and long via Updaterator

---

mock-ee/src/test/java/gov/va/api/health/mockee/Updaterator.java

https://vasdvp.atlassian.net/browse/CCE-146

CCE-146 Populate geocodeDate and addressChangeDateTime in Mock-EE data

---

mock-ee/src/test/java/gov/va/api/health/mockee/Updaterator.java

https://vasdvp.atlassian.net/browse/CCE-154

CCE-154 Updaterator edits XML directly.

---

mock-ee/src/main/resources/data/37000072.xml

https://vasdvp.atlassian.net/browse/SSS-51

SSS-51 Add record for patient that is not near any VA medical centers

---

mock-ee/src/main/resources/data/1012845331V153043.xml
mock-ee/src/main/resources/data/1012845944V882130.xml
mock-ee/src/main/resources/data/1012846043V576341.xml
mock-ee/src/main/resources/data/1012853550V207686.xml
mock-ee/src/main/resources/data/1013120787V412913.xml
mock-ee/src/main/resources/data/1013120805V887530.xml
mock-ee/src/main/resources/data/1013120820V528557.xml
mock-ee/src/main/resources/data/1013120824V310629.xml
mock-ee/src/main/resources/data/1013120826V646496.xml
mock-ee/src/main/resources/data/1013120843V483057.xml
mock-ee/src/main/resources/data/1013120844V699512.xml
mock-ee/src/main/resources/data/1013124304V115761.xml

https://vasdvp.atlassian.net/browse/SSS-73
VAOS requested additional test patients. Note that these are all eligible for community care by their codes, so no addresses are necessary.

SSS-73 Additional test patients for VAOS

---

mock-ee/src/main/java/gov/va/api/health/mockee/EeResponseEntity.java
mock-ee/src/main/java/gov/va/api/health/mockee/WebServiceConfig.java
mock-ee/src/test/java/gov/va/api/health/mockee/EeSummaryEndpointTest.java

https://vasdvp.atlassian.net/browse/SSS-75

SSS-75 Test clean-up

---

mock-ee/src/main/resources/data/1012845943V900681.xml
mock-ee/src/main/resources/data/1012853802V084487.xml
mock-ee/src/main/resources/data/1013120789V744707.xml
mock-ee/src/main/resources/data/1013125218V696863.xml

https://vasdvp.atlassian.net/browse/SSS-84

SSS-84 VAOS updates

---

mock-ee/src/main/resources/data/1013120835V054496.xml

https://vasdvp.atlassian.net/browse/SSS-85

SSS-85 VAOS updates

---

mock-ee/src/main/resources/data/1013120805V887530.xml
mock-ee/src/main/resources/data/1013120820V528557.xml
mock-ee/src/main/resources/data/1013120824V310629.xml
mock-ee/src/main/resources/data/1013120844V699512.xml

https://vasdvp.atlassian.net/browse/SSS-102

update codes for requested patient ICNs

---

mock-ee/src/main/resources/data/1013174702V548786.xml
mock-ee/src/main/resources/data/1013174708V636001.xml

https://vasdvp.atlassian.net/browse/SSS-103

Added in two new patients

---

.gitignore
mock-ee-tests/pom.xml
mock-ee/pom.xml
mock-ee/src/test/java/gov/va/api/health/mockee/Updaterator.java
pom.xml

https://vasdvp.atlassian.net/browse/SHANK-271
Drop SNAPSHOTs after https://github.com/department-of-veterans-affairs/health-apis-parent/pull/49 merges

SHANK-271 upgrade parent

---

CODEOWNERS
mock-ee-tests/src/main/docker/Dockerfile

Updated Dockerfile to inherit from vasdvp/health-apis-centos:7

Support VA Certs

---

mock-ee-tests/pom.xml
mock-ee/pom.xml
pom.xml

https://vasdvp.atlassian.net/browse/SHANK-315

SHANK-315 6.0 parent upgrade

---

Jenkinsfile
mock-ee-tests/src/main/docker/Dockerfile

https://vasdvp.atlassian.net/browse/SHANK-334

update maven image

---

mock-ee/src/main/resources/data/1008679665V880686.xml

https://vajira.max.gov/browse/API-987

API-1073 Test patient for CCE health-check

---

mock-ee/src/main/resources/data/1012880127V376982.xml

https://vajira.max.gov/browse/API-1990

API-1990 update 1012880127V376982

---

README.md

Update sample request to include cURL and add link to WSDL.
FYI @esubocz-va

Add WSDL url to documentation

---

.mvn/jvm.config
mock-ee/src/main/resources/application.properties

API-000-expose-actuator-info

---

Jenkinsfile
mock-ee-tests/pom.xml
mock-ee/pom.xml
mock-ee/src/main/java/gov/va/api/health/mockee/Application.java
mock-ee/src/main/java/gov/va/api/health/mockee/EeResponseEntity.java
mock-ee/src/main/java/gov/va/api/health/mockee/EeSummaryEndpoint.java
mock-ee/src/main/java/gov/va/api/health/mockee/WebServiceConfig.java
pom.xml

https://vajira.max.gov/browse/API-7666

Mock ee java 16 upgrade.
